### ISSUE TITLE
shownotes.raw.md instead of (or as alternative to) shownotes.raw

### ISSUE THREAD

**Issue by ghost** [ttscoff/podtagger#1]
Hi Brett,

Is it possible to have a `shownotes.raw.md` instead of (or as alternative to) `shownotes.raw`, so that the text editors (and macOS itself) detects it properly as a Markdown file?

Thank you for this tool which really helped with my podcast files! 😃

**Comment by ttscoff** [comment]
New version uses shownotes.raw.md (but still recognizes shownotes.raw as a fallback). Drag and drop app version available as well. http://brettterpstra.com/projects/podtagger
